### ISSUE TITLE
Recording struct

### ISSUE THREAD

**Issue by fjebaker** [mmesiti/Recorder.jl#1]
Could
```julia
return_values = Dict{String,Vector{Any}}()
argumentss = Dict{String,Vector{Any}}()
argumentss_post = Dict{String,Vector{Any}}()
call_number = Dict{String,Int32}()
```
be wrapped into a user instantiable struct, and then have
```julia
res = @record state=my_state func(args)
create_regression_tests(my_state)
```
that dumps all regression tests in `my_state`?

Then it would be easier to generate multiple distinct regression test scripts.

The struct could also have some configuration variables, such as if `@testset verbose = true` should be true or not, or the modifications you mention in the README, e.g., whether to use `approx` or `==`.

**Comment by mmesiti** [comment]
I might be missing something about this
```julia
res = @record state=my_state func(args)
create_regression_tests(my_state)
```

**Comment by mmesiti** [comment]
w

**Comment by mmesiti** [comment]
Apart from my clumsiness with github issues: to my understanding, something like this 
```
res = @record state=my_state func(args)
create_regression_tests(my_state)
```
would require the variable `my_state` to be local to the scope where `@record` was called, which could be buried deep down a call stack. `create_regression_tests` would instead be typically called from the REPL (Full disclosure: "typically" means "all the 3 times I have used this package so far"). How could I pass the recorded data to `create_regression_tests`?
I can see two possibilities:
1. Pass `my_state` up the call stack. But might require changing /a lot/ of code and make the package very tedious to use. 
2. Store the recorded state in the global scope of the `Recorder` module. This might be done better than in the current implementation, I guess, although the key used is `modulename.funcname`, which should be good enough (although it does not specify a particular method).

Am I missing any potential issue?

**Comment by mmesiti** [comment]
> Then it would be easier to generate multiple distinct regression test scripts.

I could add the possibility of "tagging" `@record`s, like
```
res1 = @record "tag1" func(args)


res2 = @record "tag2" func(args)
```
So that then it would be possible to call `create_regression_tests("tag1","module.func")` to create a testset/data only for the first call, and `create_regression_tests("tag2","module.func")` to create a testet/data only for the second call.

**Comment by fjebaker** [comment]
So I'd like to be able to have some files that I used to condition my regression tests, that would contain something like
```julia
using Recorder
using MyPackage

# ... do MyPackage specific things

# record some regression tests that all do a conceptually similar thing
milk = @record milk_cow(cow)
butter = @record churn_butter(milk)
... 

# record more tests that do a conceptually very different thing
ore = @record mine_ore(pickaxe)
iron = @record smelt_ore(ore)
...
```

Then, to generate my tests, I would need several successive calls to `create_regression_tests` with all of my different module functions, and end up with a single file per function.

What I'd think would be cool to have is something like
```julia
farming = RecorderState()
mining = RecorderState()

# record some regression tests that all do a conceptually similar thing
milk = @record state=farming milk_cow(cow)
butter = @record state=farming churn_butter(milk)
... 

# record more tests that do a conceptually very different thing
ore = @record state=mining mine_ore(pickaxe)
iron = @record state=mining smelt_ore(ore)
...

create_regression_tests(farming) # outputs a single file with my conceptually similar tests
create_regression_tests(mining) # outputs another single file
```
Then I could check this generator into VC, and use it to reproducibly generate new regression tests when I suddenly realize that the milk was spoiled all along.

This is vaguely inspired by how BenchmarkTools.jl does benchmarking suites.

Does that make sense as a use case?

You can also still have a global state in Recorder that is used if `state=` is not passed that defaults to the current behaviour.

**Comment by mmesiti** [comment]
This is something I haven't thought of, and it definitely makes sense to implement this.

**Comment by mmesiti** [comment]
This feature is sort-of implemented, albeit with a different syntax. What do you think @fjebaker ? Can I close this issue?

**Comment by fjebaker** [comment]
Looks good to me! So the syntax is as in your tests:

```julia
mystate = Recorder.State()
@record mystate identity(5)
@record mystate f3arg(4,5,6)
```

My only question now is whether there is a possible bug since the record with state macro is defined as 
```julia
macro record(state_expr::Symbol, expr::Expr)
    _record_expr(expr,state_expr)
end
```

meaning I can't be lazy and do:
```julia
@record Recorder.State() identity(5)
```
Since that would trigger the `record(::Expr, ::Expr)` method?

**Comment by mmesiti** [comment]
I am not really satisfied with how I manage the optionality of the arguments to `@record`, and this _escamotage_ with types (`Symbol` to match the state, `Expr` to match the range) was the first (working) thing that came to mind.

I am not exactly sure in what sense you could be lazy with `@record Recorder.State() identity(5)`. In this way, you're not saving the result of `Recorder.State()` anywhere, so how can you use it? To be super lazy, one can just rely on the global Recorder state (i.e., the `Recorder.gs` variable) - use `Recorder.clear()` to empty it before, and omit any state from the `@record` call. 

I think that it would be good to add a validation mechanism that makes sure that when `record(::Expr,::Expr)` is invoked, the first `Expr` should be a range expr. (i.e., ~`range_expr.head == :(:)`~ `range_expr.args[1] == :(:)` or something like this).

It would be cooler, possibly, to also accept the keyworded syntax `@record state=mystate range=13:2:17 <expr>`, but it's would require quite some additional boilerplate and not be particularly more transparent after all.

**Comment by fjebaker** [comment]
> I think that it would be good to add a validation mechanism that makes sure that when record(::Expr,::Expr) is invoked, the first Expr should be a range expr. (i.e., range_expr.head == :(:) or something like this).

That would be absolutely fine. Just to have some clear error message saying "Assign the state to a symbol and pass that" instead of the cryptic stack trace.

And yes, my lazy example was bad. You could imagine something like

```julia
my_states = Dict("thingA" => Recorder.State(), "thingB" => Recorder.State())
@record my_states["thingA"] identity(5)
```

etc., in which case a helpful error message would be ideal.

**Comment by fjebaker** [comment]
If you did want to be really snazzy, and I mention this more for posterity / pedagogy than as an actual suggestion, you could use `@generated` functions to generate compile time code that dispatches on types instead of the AST (bad idea but worth knowing about), or else use [MacroTools.jl](https://github.com/FluxML/MacroTools.jl) to make writing expressive macros with `state=my_state` a little less boilerplate-y.

**Comment by mmesiti** [comment]
> > I think that it would be good to add a validation mechanism that makes sure that when record(::Expr,::Expr) is invoked, the first Expr should be a range expr. (i.e., range_expr.head == :(:) or something like this).
> 
> That would be absolutely fine. Just to have some clear error message saying "Assign the state to a symbol and pass that" instead of the cryptic stack trace.
> 
> And yes, my lazy example was bad. You could imagine something like
> 
> ```julia
> my_states = Dict("thingA" => Recorder.State(), "thingB" => Recorder.State())
> @record my_states["thingA"] identity(5)
> ```
> 
> etc., in which case a helpful error message would be ideal.

I see. I think that being able to use an expression for the state argument could be more important than I originally envisaged if the `@record` macro has to stay in  the code "for good" after the regression tests have been created.

> If you did want to be really snazzy, and I mention this more for posterity / pedagogy than as an actual suggestion, you could use `@generated` functions to generate compile time code that dispatches on types instead of the AST (bad idea but worth knowing about), or else use [MacroTools.jl](https://github.com/FluxML/MacroTools.jl) to make writing expressive macros with `state=my_state` a little less boilerplate-y.

In case I - or someone else - end up using this more often, I will for sure try to make things more elegant. Thanks for the suggestions, I will have a look.
I will mention these remaining ideas in the README in the "Possible Features" section.
