### ISSUE TITLE
Possible issues with Serialization

### ISSUE THREAD

**Issue by mmesiti** [mmesiti/Recorder.jl#3]
From the documentation of the Serialization package, deserialization might fail between minor julia releases.

> The data format can change in minor (1.x) Julia releases, but files written by prior 1.x versions will remain readable. The main exception to this is when the definition of a type in an external package changes. If that occurs, it may be necessary to specify an explicit compatible version of the affected package in your environment. Renaming functions, even private functions, inside packages can also put existing files out of sync.

So there are some possible approaches to this:
- give the possibility to the user to specify their own serializers
- do some expectation management in the documentation (this requires understanding exactly what the problems are/might be).

Thanks to @NilsNiggemann for pointing this out.

**Comment by NilsNiggemann** [comment]
Perhaps one can do something with JLD2 as an opt-in, if one wants to be more lenient on changes?
Strictly speaking they also require no changes of types but I think there are some useful heuristics

```
import JLD2
module Mod
    struct teststruct 
        x::Vector{Float64}
    end
end

SomeData = Mod.teststruct(rand(4))
JLD2.@save "SomeData.jld2" SomeData

module Mod
    struct teststruct 
        x::Vector{Float32}
    end
end
oldSomeData = deepcopy(SomeData)
JLD2.@load "SomeData.jld2"
println(SomeData.x ≈ oldSomeData.x)
```
Output
```
WARNING: replacing module Mod.
true
```
if the struct changes drastically there will still be errors of course (which would be what we want after all)
